theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
exclude:
  - .bundle/
  - .dockerignore
  - .jekyll-cache/
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - start.sh
  - vendor/
